table HR_Analytics

	measure 'Employee Count' = DISTINCTCOUNT ( HR_Analytics[EmpID] )
		formatString: #,##0

	measure 'Total Employees' = [Employee Count]
		formatString: #,##0

	measure 'Active Employees' = CALCULATE ( [Employee Count], HR_Analytics[Attrition] = "No" )
		formatString: #,##0

	measure 'Total Attrition' = CALCULATE ( [Employee Count], HR_Analytics[Attrition] = "Yes" )
		formatString: #,##0

	measure 'Attrition Rate %' = DIVIDE ( [Total Attrition], [Total Employees] )
		formatString: 0.0%

	measure 'Average Monthly Income' = AVERAGEX ( VALUES ( HR_Analytics[EmpID] ), CALCULATE ( MAX ( HR_Analytics[MonthlyIncome] ) ) )
		formatString: \$#,##0;(\$#,##0);\$#,##0

	measure 'Average Age' = AVERAGEX ( VALUES ( HR_Analytics[EmpID] ), CALCULATE ( MAX ( HR_Analytics[Age] ) ) )
		formatString: 0.0

	measure 'Average Tenure' = AVERAGEX ( VALUES ( HR_Analytics[EmpID] ), CALCULATE ( MAX ( HR_Analytics[YearsAtCompany] ) ) )
		formatString: 0.0

	measure 'Average Job Satisfaction' = AVERAGEX ( VALUES ( HR_Analytics[EmpID] ), CALCULATE ( MAX ( HR_Analytics[JobSatisfaction] ) ) )
		formatString: 0.0

	measure 'Average Environment Satisfaction' = AVERAGEX ( VALUES ( HR_Analytics[EmpID] ), CALCULATE ( MAX ( HR_Analytics[EnvironmentSatisfaction] ) ) )
		formatString: 0.0

	measure 'Overtime %' = DIVIDE ( CALCULATE ( [Employee Count], HR_Analytics[OverTime] = "Yes" ), [Total Employees] )
		formatString: 0.0%

	measure 'Active Average Monthly Income' = CALCULATE ( [Average Monthly Income], HR_Analytics[Attrition] = "No" )
		formatString: \$#,##0;(\$#,##0);\$#,##0

	measure 'Active Average Tenure' = CALCULATE ( [Average Tenure], HR_Analytics[Attrition] = "No" )
		formatString: 0.0

	measure 'Active Average Job Satisfaction' = CALCULATE ( [Average Job Satisfaction], HR_Analytics[Attrition] = "No" )
		formatString: 0.0

	measure 'Active Average Environment Satisfaction' = CALCULATE ( [Average Environment Satisfaction], HR_Analytics[Attrition] = "No" )
		formatString: 0.0

	measure 'Duplicate EmpID Count' = COUNTROWS ( FILTER ( VALUES ( HR_Analytics[EmpID] ), CALCULATE ( COUNTROWS ( HR_Analytics ) ) > 1 ) )
		formatString: #,##0

	measure 'Attrition Analysis Title' = "Attrition Analysis — " & COALESCE ( SELECTEDVALUE ( HR_Analytics[Department] ), "All Departments" )
		formatString: @

	measure 'Active Overtime %' = DIVIDE ( CALCULATE ( [Employee Count], HR_Analytics[Attrition] = "No", HR_Analytics[OverTime] = "Yes" ), [Active Employees] )
		formatString: 0.0%

	measure 'Attrition Overtime %' = DIVIDE ( CALCULATE ( [Employee Count], HR_Analytics[Attrition] = "Yes", HR_Analytics[OverTime] = "Yes" ), [Total Attrition] )
		formatString: 0.0%

	measure 'Average Work Life Balance' = AVERAGEX ( VALUES ( HR_Analytics[EmpID] ), CALCULATE ( MAX ( HR_Analytics[WorkLifeBalance] ) ) )
		formatString: 0.0

	measure 'Active Average Work Life Balance' = CALCULATE ( [Average Work Life Balance], HR_Analytics[Attrition] = "No" )
		formatString: 0.0

	column EmpID
		dataType: string
		summarizeBy: none
		sourceColumn: EmpID

	column Age
		dataType: int64
		summarizeBy: none
		sourceColumn: Age

	column AgeGroup
		dataType: string
		summarizeBy: none
		sourceColumn: AgeGroup

	column Attrition
		dataType: string
		summarizeBy: none
		sourceColumn: Attrition

	column BusinessTravel
		dataType: string
		summarizeBy: none
		sourceColumn: BusinessTravel

	column DailyRate
		dataType: int64
		summarizeBy: sum
		sourceColumn: DailyRate

	column Department
		dataType: string
		summarizeBy: none
		sourceColumn: Department

	column DistanceFromHome
		dataType: int64
		summarizeBy: sum
		sourceColumn: DistanceFromHome

	column Education
		dataType: int64
		summarizeBy: none
		sourceColumn: Education

	column EducationField
		dataType: string
		summarizeBy: none
		sourceColumn: EducationField

	column EmployeeCount
		dataType: int64
		summarizeBy: none
		sourceColumn: EmployeeCount

	column EmployeeNumber
		dataType: int64
		summarizeBy: none
		sourceColumn: EmployeeNumber

	column EnvironmentSatisfaction
		dataType: int64
		summarizeBy: none
		sourceColumn: EnvironmentSatisfaction

	column Gender
		dataType: string
		summarizeBy: none
		sourceColumn: Gender

	column HourlyRate
		dataType: int64
		summarizeBy: sum
		sourceColumn: HourlyRate

	column JobInvolvement
		dataType: int64
		summarizeBy: none
		sourceColumn: JobInvolvement

	column JobLevel
		dataType: int64
		summarizeBy: none
		sourceColumn: JobLevel

	column JobRole
		dataType: string
		summarizeBy: none
		sourceColumn: JobRole

	column JobSatisfaction
		dataType: int64
		summarizeBy: none
		sourceColumn: JobSatisfaction

	column MaritalStatus
		dataType: string
		summarizeBy: none
		sourceColumn: MaritalStatus

	column MonthlyIncome
		dataType: int64
		summarizeBy: sum
		sourceColumn: MonthlyIncome

	column SalarySlab
		dataType: string
		summarizeBy: none
		sourceColumn: SalarySlab

	column MonthlyRate
		dataType: int64
		summarizeBy: sum
		sourceColumn: MonthlyRate

	column NumCompaniesWorked
		dataType: int64
		summarizeBy: sum
		sourceColumn: NumCompaniesWorked

	column Over18
		dataType: string
		summarizeBy: none
		sourceColumn: Over18

	column OverTime
		dataType: string
		summarizeBy: none
		sourceColumn: OverTime

	column PercentSalaryHike
		dataType: int64
		summarizeBy: sum
		sourceColumn: PercentSalaryHike

	column PerformanceRating
		dataType: int64
		summarizeBy: none
		sourceColumn: PerformanceRating

	column RelationshipSatisfaction
		dataType: int64
		summarizeBy: none
		sourceColumn: RelationshipSatisfaction

	column StandardHours
		dataType: int64
		summarizeBy: none
		sourceColumn: StandardHours

	column StockOptionLevel
		dataType: int64
		summarizeBy: none
		sourceColumn: StockOptionLevel

	column TotalWorkingYears
		dataType: int64
		summarizeBy: sum
		sourceColumn: TotalWorkingYears

	column TrainingTimesLastYear
		dataType: int64
		summarizeBy: sum
		sourceColumn: TrainingTimesLastYear

	column WorkLifeBalance
		dataType: int64
		summarizeBy: none
		sourceColumn: WorkLifeBalance

	column YearsAtCompany
		dataType: int64
		summarizeBy: sum
		sourceColumn: YearsAtCompany

	column YearsInCurrentRole
		dataType: int64
		summarizeBy: sum
		sourceColumn: YearsInCurrentRole

	column YearsSinceLastPromotion
		dataType: int64
		summarizeBy: sum
		sourceColumn: YearsSinceLastPromotion

	column YearsWithCurrManager
		dataType: int64
		summarizeBy: sum
		sourceColumn: YearsWithCurrManager

	partition HR_Analytics = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents("C:\\Users\\Eslam\\Documents\\Codex\\2026-10-03\\files-mentioned-by-the-user-hr\\outputs\\HR_Analytics_Dashboard\\Data\\HR_Analytics.csv"),[Delimiter=",", Columns=38, Encoding=65001, QuoteStyle=QuoteStyle.Csv]),
				    PromotedHeaders = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    ChangedType = Table.TransformColumnTypes(PromotedHeaders,{{"EmpID", type text}, {"Age", Int64.Type}, {"AgeGroup", type text}, {"Attrition", type text}, {"BusinessTravel", type text}, {"DailyRate", Int64.Type}, {"Department", type text}, {"DistanceFromHome", Int64.Type}, {"Education", Int64.Type}, {"EducationField", type text}, {"EmployeeCount", Int64.Type}, {"EmployeeNumber", Int64.Type}, {"EnvironmentSatisfaction", Int64.Type}, {"Gender", type text}, {"HourlyRate", Int64.Type}, {"JobInvolvement", Int64.Type}, {"JobLevel", Int64.Type}, {"JobRole", type text}, {"JobSatisfaction", Int64.Type}, {"MaritalStatus", type text}, {"MonthlyIncome", Int64.Type}, {"SalarySlab", type text}, {"MonthlyRate", Int64.Type}, {"NumCompaniesWorked", Int64.Type}, {"Over18", type text}, {"OverTime", type text}, {"PercentSalaryHike", Int64.Type}, {"PerformanceRating", Int64.Type}, {"RelationshipSatisfaction", Int64.Type}, {"StandardHours", Int64.Type}, {"StockOptionLevel", Int64.Type}, {"TotalWorkingYears", Int64.Type}, {"TrainingTimesLastYear", Int64.Type}, {"WorkLifeBalance", Int64.Type}, {"YearsAtCompany", Int64.Type}, {"YearsInCurrentRole", Int64.Type}, {"YearsSinceLastPromotion", Int64.Type}, {"YearsWithCurrManager", Int64.Type}})
				in
				    ChangedType

